language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - pip install --upgrade pip
  - "pip install .[dev]"
before_script:
  - pip freeze
script:
  - make linter
  - make test
